// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsJpZP8qYTanydjlg_kxLyO1BNfzjw7tQ',
    appId: '1:177628054151:web:f17acc8611a6401a24ae22',
    messagingSenderId: '177628054151',
    projectId: 'tag-game-6f59e',
    authDomain: 'tag-game-6f59e.firebaseapp.com',
    storageBucket: 'tag-game-6f59e.firebasestorage.app',
    measurementId: 'G-SG6Z1CS65S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR8mvXTJq_uCoqNvp3G8OGVav_-sWx1w8',
    appId: '1:177628054151:android:e4d24fffbb4dbf4924ae22',
    messagingSenderId: '177628054151',
    projectId: 'tag-game-6f59e',
    storageBucket: 'tag-game-6f59e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Sz5W6YT8p11TPE7v6-dQiIvOkqgbQj0',
    appId: '1:177628054151:ios:dfd09c1a1c7289fa24ae22',
    messagingSenderId: '177628054151',
    projectId: 'tag-game-6f59e',
    storageBucket: 'tag-game-6f59e.firebasestorage.app',
    iosBundleId: 'com.example.tagGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Sz5W6YT8p11TPE7v6-dQiIvOkqgbQj0',
    appId: '1:177628054151:ios:dfd09c1a1c7289fa24ae22',
    messagingSenderId: '177628054151',
    projectId: 'tag-game-6f59e',
    storageBucket: 'tag-game-6f59e.firebasestorage.app',
    iosBundleId: 'com.example.tagGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsJpZP8qYTanydjlg_kxLyO1BNfzjw7tQ',
    appId: '1:177628054151:web:067c61d518f5fdac24ae22',
    messagingSenderId: '177628054151',
    projectId: 'tag-game-6f59e',
    authDomain: 'tag-game-6f59e.firebaseapp.com',
    storageBucket: 'tag-game-6f59e.firebasestorage.app',
    measurementId: 'G-MS5CXR1XWW',
  );
}
